// <auto-generated />
namespace NOVA_VERZIJA_IT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class stefcee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stefcee));
        
        string IMigrationMetadata.Id
        {
            get { return "202408052237565_stefcee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
